// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwhfeezspurzleomwgmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aGZlZXpzcHVyemxlb213Z215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDcxNDgsImV4cCI6MjA2ODgyMzE0OH0.Bgxk1eU6ls6jBouRD5I3Xd_OMYJ58N8Yo-3N3qxlikE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});